#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake

cd twoPhaseMixingCentralDyMFoam; wmake; cd ../


# ----------------------------------------------------------------- end-of-file
