#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

touch dam.foam
restore0Dir
runApplication blockMesh
runApplication setFields
runApplication $(getApplication)

#------------------------------------------------------------------------------
