#!/bin/sh

cd pimpleCentral; wclean; wcleanLnIncludeAll; cd ../

cd pimpleCentralFoam; ./Allwclean; cd ../

cd reactingPimpleCentralFoam; ./Allwclean; cd ../

cd twoPhaseMixingCentralFoam; ./Allwclean; cd ../

cd chtMultiRegionCentralFoam; ./Allwclean; cd ../

cd interTwoPhaseCentralFoam; ./Allwclean; cd ../

cd vofTwoPhaseCentralFoam; ./Allwclean; cd ../

#
#END-OF-FILE
#

