#!/bin/sh

cd pimpleCentral; wmake libso; cd ../

cd pimpleCentralFoam; ./Allwmake; cd ../

cd reactingPimpleCentralFoam; ./Allwmake; cd ../

cd reactingLagrangianPimpleCentralFoam; ./Allwmake; cd ../

cd twoPhaseMixingCentralFoam; ./Allwmake; cd ../

cd chtMultiRegionCentralFoam; ./Allwmake; cd ../

cd interTwoPhaseCentralFoam; ./Allwmake; cd ../

#
#END-OF-FILE
#


