#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch Test4.foam
runApplication blockMesh
runApplication setFields
runApplication `getApplication`
runApplication postProcess -func sampleDict

#------------------------------------------------------------------------------
