#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch bstep.foam
cp -rf 0.orig 0
runApplication blockMesh
runApplication `getApplication`
runApplication postProcess -func sampleDict

#------------------------------------------------------------------------------
