#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0
cp -rf 0.orig/ 0/
touch backwardStep.foam
runApplication blockMesh
runApplication `getApplication`

#------------------------------------------------------------------------------
