#!/bin/bash

cd RiemanToro

RTCASES=`ls`
for RTCASE in $RTCASES
do
    cd $RTCASE
    ./Allclean
    cd ../
done
cd ../

cd ConvergingDivergingNozzle; ./Allclean; cd ../

cd ForwardStep; ./Allclean; cd ../

cd gasMixture; ./Allclean; cd ../

cd oscillatingInlet; ./Allclean; cd ../

#
#END-OF-FILE
#

