#!/bin/bash

cd RiemanToro

RTCASES=`ls`
for RTCASE in $RTCASES
do
    cd $RTCASE
    ./Allrun
    cd ../
done
cd ../

cd ConvergingDivergingNozzle; ./Allrun; cd ../

cd ForwardStep; ./Allrun; cd ../

cd gasMixture; ./Allrun; cd ../

cd oscillatingInlet; ./Allrun; cd ../


#
#END-OF-FILE
#

