#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake

# cd pisoCentralDyMFoam; wmake; cd ../
# cd rhoPisoCentralFoam; wmake; cd ../

# ----------------------------------------------------------------- end-of-file
