#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean
# cd pisoCentralDyMFoam; wclean; cd ../
# cd rhoPisoCentralFoam; wclean; cd ../


# ----------------------------------------------------------------- end-of-file
