#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

tar xfz constant/polyMesh.tgz
mv polyMesh constant/
runApplication setFields
runApplication `getApplication`
runApplication postProcess -func sampleDict

#------------------------------------------------------------------------------
