#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd jumpingCylinderFunctionObject; wmake; cd ../

cd constant; tar xfz polyMesh.tgz; cd ../
runApplication `getApplication`
#runApplication postProcess -func sampleDict

#------------------------------------------------------------------------------
