#!/bin/sh

cd pisoCentral; wclean; wcleanLnIncludeAll; cd ../

cd pimpleCentralFoam; ./Allwclean; cd ../

cd reactingPimpleCentralFoam; ./Allwclean; cd ../

#cd twoPhaseMixingCentralFoam; wclean;
#cd twoPhaseMixingCentralDyMFoam; wclean; cd ../../

#
#END-OF-FILE
#

