#!/bin/sh

cd pisoCentral; wmake libso; cd ../

cd pimpleCentralFoam; ./Allwmake; cd ../

cd reactingPimpleCentralFoam; ./Allwmake; cd ../

cd twoPhaseMixingCentralFoam; ./Allwmake; cd ../

#
#END-OF-FILE
#


