#!/bin/sh

cd pisoCentral; wmake libso; cd ../

cd pimpleCentralFoam; ./Allwmake; cd ../

#cd twoPhaseMixingCentralFoam; wmake;
#cd twoPhaseMixingCentralDyMFoam; wmake;
#cd ../../

#
#END-OF-FILE
#


