#!/bin/sh

cd pisoCentral; wclean; wcleanLnIncludeAll; cd ../

cd pimpleCentralFoam; ./Allwclean; cd ../

cd reactingPimpleCentralFoam; ./Allwclean; cd ../

cd twoPhaseMixingCentralFoam; ./Allwclean; cd ../

cd chtMultiRegionCentralFoam; ./Allwclean; cd ../

#
#END-OF-FILE
#

