name: Starts testing of pimpleCentralFoam (dev branch)

on:
  push

jobs:
  start-VnV-pimpleCentralFoam:
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'
    steps:
      - name: Fire event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.VNVEXECUTE }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/mkraposhin/VnV/dispatches \
            -d '{"event_type":"check-pimpleCentralFoam-dev"}'
